spring.application.name=virtual-fitting

# MariaDB 연결 설정
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# localhost:3306 뒤에 DBeaver에서 만든 데이터베이스 이름을 적어주세요
spring.datasource.url=jdbc:mariadb://localhost:3306/virtual_fitting
spring.datasource.username=root
spring.datasource.password=tmdals123!

# JPA 설정 (테이블 자동 생성 옵션)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true